### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by joker-x**

### CODE REVIEW

**Review by boazpoolman — CHANGES_REQUESTED** [review]
This looks great @joker-x!
Thanks for submitting this PR.

I see that the Eslint job is failing.
Could you fix those?
If those are fixed we can merge this PR.

**Comment by joker-x** [comment]
It has been a pleasure. A minuscule contribution compared to the hours of work your plugin has saved me. Thank you so much!

In the last commit I tried to fix the Eslint errors but I did not know how to run the tests locally.

**Review by boazpoolman — APPROVED** [review]
The Eslint job is fixed. Nice work.

For future reference:
You can run Eslint locally by running it's CLI.
A repository like this usually has an `eslint` script defined in it's package.json ([see here](https://github.com/boazpoolman/strapi-plugin-config-sync/blob/master/package.json#L17)). 
You can fire that by running:
```
yarn run eslint
```

**Comment by joker-x** [comment]
@boazpoolman i ran eslint locally sucessfull, thanks!

**Pull request merged**
