### PR TITLE
Fix import of button from @strapi/design-system

### PR DESCRIPTION
**Pull request by diacu**
Fix issue #83 by updating how Button is imported from @strapi/design-system.

### CODE REVIEW

**Comment by boazpoolman** [comment]
Hey @diacu,

Thank you for reporting the issue.
I’ve ran the CI on your PR and as I expected it failed on linting because the updated button import is unresolved.

See the failed CI output here https://github.com/boazpoolman/strapi-plugin-config-sync/actions/runs/3974200216/jobs/6813678040

I’ll try to reproduce the issue but I can’t imagine updating the button import fixes the issue.

EDIT:
Please refer to the design system docs on how to import the button component. https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-button--base

It states the import should be written like this:

import { Button } from '@strapi/design-system';

**Comment by diacu** [comment]
Hey @boazpoolman,

   I checked the docs too, but what made me try this was that other plugins and strapi core is importing buttons the same way. I don't know why they do it like this, I did not find anything related to this on strapi/strapi repo. 
   I didn't run any tests, I just did the changes in my node_modules, saw that it works and forked the repo to share my findings with you.

**Comment by boazpoolman** [comment]
The import guidelines of all the design-system components were updated in [this commit](https://github.com/strapi/design-system/commit/2f878b6dd70eb37d94a11cb876dbbd8df5364888). Both ways of importing still work for backwards compatibility I assume, though they've made it so that linting will fail if you use the old way so you're forced into using the new way.
Having said that, many plugins including core plugins have not been fully updated to use the new format.

I suspect something else broke you're instance and updating the node modules helped reload and fix it. Can you confirm that if you revert your change in the node modules that the issue comes back?

**Comment by diacu** [comment]
I found the problem by adding all my project dependencies into the playground and run everything. I have a plugin that somehow forces the version of @strapi/design-system to 1.2.5 (it's strapi-plugin-comment-manager). Removing it solve the problem, so it's not a bug on your plugin. 

Thanks a lot for your help!

**Pull request closed without merging**
